version: 2
jobs:
  test:
    docker:
      - image: circleci/node:12.16.1
      - image: ethereum/client-go
        entrypoint: /bin/sh
        command: -c "yes '' | geth --dev --dev.period 15 --http --http.addr '0.0.0.0' --http.port 8545 --http.api 'eth,net,web3,account,admin,personal' --unlock '0' --allow-insecure-unlock"
    steps:
      - checkout
      - run: |
          yarn install
          yarn test

  publishDryRun:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Check Package Version Valid on NPM
          command: ./.circleci/check_npm_version.sh

  publish:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/.npmrc
      - run:
          name: Publish package
          command: |
            # Sometimes we just wanna update the readme file
            if ./.circleci/check_npm_version.sh; then
                npm publish --ignore-scripts --access public
            fi

workflows:
  version: 2
  test-publish:
    jobs:
      - test
      - publishDryRun:
          requires:
            - test
          filters:
            branches:
              ignore:
                - master
      - publish:
          requires:
            - test
          filters:
            branches:
              only:
                - master
